name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Run system tests
      run: sudo apt-get install sqlite3 python3-dev python3-pip python3-venv python3-wheel -y && pip install wheel && make test
